name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: lct-comp-testing.tex
          args: "-f -pdf -latexoption=-shell-escape -latexoption=-file-line-error -latexoption=-interaction=nonstopmode"
      - name: Attach resume
        uses: actions/upload-artifact@v2
        with:
          name: lct-comp-testing.pdf
          path: lct-comp-testing.pdf
